### PR TITLE
Enable loading component execution scripts from custom locations

### PR DESCRIPTION
**Pull request by jazzsir**
Fixes elyra-ai/elyra#1164

Enable notebook to load component execution
scripts from custom locations via environment
variables.

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by lresende** [comment]
Thanks @jazzsir, the test failures are independent of these changes.

**Review by kevin-bates — COMMENTED** [review]
Hi @jazzsir - thank you for this contribution, it will be useful.

My only comment is that we should prefix these env names. However, rather than use the existing prefix, we're going to be refactoring this area and would prefer these be prefixed with `ELYRA_`. In fact, it would great if you could replace KFP_NOTEBOOK_ with ELYRA_ on the two existing env names as well.

Regarding the `KFP_NOTEBOOK_` replacements, I think introducing a second prefix of `GITHUB_` also makes sense, leaving `ELYRA_GITHUB_ORG` and `ELYRA_GITHUB_BRANCH` since they were missing that "context" previously.

If you prefer to keep the variable names not prefixed, I'm okay with that.  We should update the refactored variable names accordingly though - e.g., `GITHUB_ORG = ...`

Thanks!

**Comment by jazzsir** [comment]
Thanks @kevin-bates, env names were prefixed with ELYRA_

**Review by lresende — APPROVED** [review]
LGTM, will wait for the others that provided feedback to have a say as well.

**Review by kevin-bates — APPROVED** [review]
Looks great - thank you!

**Review by kevin-bates — APPROVED** [review]

**Comment by ptitzler** [comment]
It's be great if we could also create separate [documentation PR](https://elyra.readthedocs.io/en/latest/developer_guide/documentation.html) in https://github.com/elyra-ai/elyra/ that adds a new recipe (similar to https://elyra.readthedocs.io/en/latest/recipes/deploying-kubeflow-locally-for-dev.html) outlining how a user can take advantage of this enhancement.

**Review by lresende — APPROVED** [review]

**Pull request merged**
